### ISSUE TITLE
Failed joobyRun on Apple M1 Silicon

### ISSUE THREAD

**Issue by maxbertinetti** [jooby-project/jooby#2301] opened 2021-04-04 09:21 UTC
How can I resolve this?

```
✦ ➜ ./gradlew joobyRun
> Task :kaptGenerateStubsKotlin UP-TO-DATE
> Task :kaptKotlin UP-TO-DATE
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :joobyRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':joobyRun'.
> /Users/max/Library/Caches/JNA/temp/jna7013481395428920527.tmp: dlopen(/Users/max/Library/Caches/JNA/temp/jna7013481395428920527.tmp, 1): no suitable image found.  Did find:
  	/Users/max/Library/Caches/JNA/temp/jna7013481395428920527.tmp: no matching architecture in universal wrapper
  	/Users/max/Library/Caches/JNA/temp/jna7013481395428920527.tmp: no matching architecture in universal wrapper
```

**Comment by maxbertinetti** [comment] 2021-04-04 09:22
```
✦ ➜ java -version
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)
```

**Comment by maxbertinetti** [comment] 2021-04-04 09:24
Sorry I see is a problem with JNA, not Jooby itself.

**Comment by ludmiloff** [comment] 2021-04-04 11:31
Sorry to write on closed issue. 
Want to know is there any solution about this?

**Comment by maxbertinetti** [comment] 2021-04-04 11:43
Yes, if possible.Il 04 apr 2021 13:31, Cvetoslav Ludmiloff ***@***.***> ha scritto:
Sorry to write on closed issue.
Want to know is there any solution about this?

**Comment by maxbertinetti** [comment] 2021-04-04 11:43
Yes, if possible.

**Comment by ludmiloff** [comment] 2021-04-04 17:27
From what I've read about the issue in other threads, it is possibly related to the file watcher in dev mode, e.g. ```mvn jooby:run```; 
However, I was able to compile without an error.

**Comment by jknack** [comment] 2021-04-05 12:21
What is the issue? is it filewatcher or JVM version?

**Comment by ludmiloff** [comment] 2021-04-05 12:30
The issue is somewhere into the filewatcher as I was able to successfully build and run a stork file.
The error occurs with jdk 1.8, 11, 16 for arm64.

<img width="896" alt="Screenshot 2021-04-05 at 15 29 01" src="https://user-images.githubusercontent.com/673583/113573925-c2bb2b00-9623-11eb-8758-987ebdc03053.png">
<img width="1286" alt="Screenshot 2021-04-05 at 15 29 36" src="https://user-images.githubusercontent.com/673583/113573929-c64eb200-9623-11eb-87c0-cf152e0833e3.png">

@jknack, I could also upload detailed debug info with -X flag

**Comment by jknack** [comment] 2021-04-05 12:42
Thanks. can you bug this in [filewatcher](https://github.com/gmethvin/directory-watcher)?

We could probably detect Apple M1 processor and probably use the JVM file watcher (bit slower than the one failing)

**Comment by ludmiloff** [comment] 2021-04-05 13:07
@jknack, I'm not sure what to report in filewatcher. According their log it might be fixed some time ago and my suggestion is wrong.

directory-watcher updated JNA to [5.6](https://github.com/gmethvin/directory-watcher/pull/53)

Here detailed log after **mvn jooby:run**:

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] --- tiles-maven-plugin: Injecting 1 tiles as intermediary parent artifacts for app:testapp...
[INFO] Mixed 'app:testapp:1.0.0' with tile 'io.jooby:jooby-stork:2.9.5' as its new parent.
[INFO] Mixed 'io.jooby:jooby-stork:2.9.5' with original parent '(no parent)' as its new top level parent.
[INFO] 
[INFO] 
[INFO] ----------------------------< app:testapp >-----------------------------
[INFO] Building testapp 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> jooby-maven-plugin:2.9.5:run (default-cli) > process-classes @ testapp >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ testapp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ testapp ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< jooby-maven-plugin:2.9.5:run (default-cli) < process-classes @ testapp <<<
[INFO] 
[INFO] 
[INFO] --- jooby-maven-plugin:2.9.5:run (default-cli) @ testapp ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.993 s
[INFO] Finished at: 2021-04-05T16:00:57+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.jooby:jooby-maven-plugin:2.9.5:run (default-cli) on project testapp: execution of run resulted in exception: /Users/cl/Library/Caches/JNA/temp/jna13493159515514004075.tmp: dlopen(/Users/cl/Library/Caches/JNA/temp/jna13493159515514004075.tmp, 1): no suitable image found.  Did find:
[ERROR] 	/Users/cl/Library/Caches/JNA/temp/jna13493159515514004075.tmp: no matching architecture in universal wrapper
[ERROR] 	/Users/cl/Library/Caches/JNA/temp/jna13493159515514004075.tmp: no matching architecture in universal wrapper
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.jooby:jooby-maven-plugin:2.9.5:run (default-cli) on project testapp: execution of run resulted in exception
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: execution of run resulted in exception
    at io.jooby.maven.BaseMojo.execute (BaseMojo.java:83)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.UnsatisfiedLinkError: /Users/cl/Library/Caches/JNA/temp/jna13493159515514004075.tmp: dlopen(/Users/cl/Library/Caches/JNA/temp/jna13493159515514004075.tmp, 1): no suitable image found.  Did find:
	/Users/cl/Library/Caches/JNA/temp/jna13493159515514004075.tmp: no matching architecture in universal wrapper
	/Users/cl/Library/Caches/JNA/temp/jna13493159515514004075.tmp: no matching architecture in universal wrapper
    at jdk.internal.loader.NativeLibraries.load (Native Method)
    at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open (NativeLibraries.java:383)
    at jdk.internal.loader.NativeLibraries.loadLibrary (NativeLibraries.java:227)
    at jdk.internal.loader.NativeLibraries.loadLibrary (NativeLibraries.java:169)
    at java.lang.ClassLoader.loadLibrary (ClassLoader.java:2383)
    at java.lang.Runtime.load0 (Runtime.java:746)
    at java.lang.System.load (System.java:1857)
    at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath (Native.java:1018)
    at com.sun.jna.Native.loadNativeDispatchLibrary (Native.java:988)
    at com.sun.jna.Native.<clinit> (Native.java:195)
    at io.methvin.watchservice.jna.CarbonAPI.<clinit> (CarbonAPI.java:20)
    at io.methvin.watchservice.jna.CFStringRef.toCFString (CFStringRef.java:23)
    at io.methvin.watchservice.MacOSXListeningWatchService.register (MacOSXListeningWatchService.java:127)
    at io.methvin.watchservice.WatchablePath.register (WatchablePath.java:50)
    at io.methvin.watcher.DirectoryWatcher.register (DirectoryWatcher.java:341)
    at io.methvin.watcher.DirectoryWatcher.registerAll (DirectoryWatcher.java:315)
    at io.methvin.watcher.DirectoryWatcher.<init> (DirectoryWatcher.java:176)
    at io.methvin.watcher.DirectoryWatcher$Builder.build (DirectoryWatcher.java:117)
    at io.jooby.run.JoobyRun.newWatcher (JoobyRun.java:310)
    at io.jooby.run.JoobyRun.start (JoobyRun.java:254)
    at io.jooby.maven.RunMojo.doExecute (RunMojo.java:115)
    at io.jooby.maven.BaseMojo.execute (BaseMojo.java:78)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by maxbertinetti** [comment] 2021-04-05 13:15
I was using gradle, not maven.

Can make some difference?

**Comment by ludmiloff** [comment] 2021-04-05 13:25
@maxbertinetti I think Gradle is also affected.

An upcoming directory watcher update https://github.com/jooby-project/jooby/commit/d7b958d8459685e128a49da9caaa9f066249e9a4#diff-2a09b6fbbc9135ab12d2da2962400b0a084bded88ec4a04bf670f10a3d289175

might resolve the issue. I'm a bit confused about in what version 0.10.x or 0.11.x they merged the patch.

**Comment by maxbertinetti** [comment] 2021-04-05 13:29
Also, different native JDK gives different problem:

Azul Zulu fail on joobyRun
BellSoft fail on build

```
➜ ./gradlew build
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :startScripts UP-TO-DATE
> Task :distTar UP-TO-DATE
> Task :distZip UP-TO-DATE
> Task :shadowJar UP-TO-DATE
> Task :startShadowScripts UP-TO-DATE
> Task :shadowDistTar UP-TO-DATE
> Task :shadowDistZip UP-TO-DATE
> Task :assemble UP-TO-DATE
> Task :compileTestKotlin UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE

> Task :test FAILED

WelcomeTest > initializationError FAILED
    com.mysql.cj.jdbc.exceptions.CommunicationsException
        Caused by: com.mysql.cj.exceptions.CJCommunicationsException
            Caused by: java.net.ConnectException

1 test completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/max/Eclecticlly/website/build/reports/tests/test/index.html

```

**Comment by maxbertinetti** [comment] 2021-04-05 13:32
Sorry, MySQL was stopped...

**Comment by jknack** [comment] 2021-04-05 13:51
@ludmiloff ok, so it is fixed in 0.15.0 (or jna was updated it there).

So we need a new jooby release.

**Comment by maxbertinetti** [comment] 2021-04-06 13:16
Thanks @jknack @ludmiloff

**Comment by maxbertinetti** [comment] 2021-04-14 12:31
@jknack do you have an idea about a release date for the next version?

Can I help in some way?

**Comment by jknack** [comment] 2021-04-14 13:51
Too busy, just need to find some time.

will try this next weekend.

Thanks.

**Comment by ludmiloff** [comment] 2021-04-14 14:58
jooby 1.6.x is not affected, which is somewhat strange

**Comment by ludmiloff** [comment] 2021-05-10 07:10
Thanks @jknack, great work. 
It working, tested both with java 1.8 and java 16

**Closed** 2021-05-10 12:41 UTC
Labels: enhancement, jooby:run
