### ISSUE TITLE
Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block while trying to access session on a WebSocket route

### ISSUE THREAD

**Issue by MrPowerGamerBR** [jooby-project/jooby#1057] opened 2018-04-10 19:47 UTC
Trying to access the user's session on a WebSocket route
```
    ws("/ws") { req, ws ->
        req.session()
    }
``` 

Throws this exception

`Caused by: com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block`

**Comment by jknack** [comment] 2018-04-16 19:36
I can't reproduce it using the https://github.com/jooby-project/websocket-starter project:

```
/** Start a websocket at /ws and send back JSON: */
    ws("/ws", (req, ws) -> {
      String sessionAttribute = req.session().get("foo").value();
      /** Send back message: */
      ws.onMessage(msg -> ws.send(new Message(sessionAttribute)));
    }).produces("json");
```

**Comment by MrPowerGamerBR** [comment] 2018-05-24 00:33
(Tried using secure WebSockets, same exception... hmmmmm, I have no idea why it wouldn't work, I'm using the latest Jooby build @ Maven (1.3.0))

**Comment by jknack** [comment] 2018-05-24 12:31
You need to access from `onConnect` handler:

```
ws("/ws", { handler, ws ->
   val test = handler.session().get("test")
})
```

not from `onMessage`

```
ws("/ws", { handler, ws ->
   ws.onMessage({ ws.send("Received Message! ${handler.session().get("test")}") });
})
```

**Comment by MrPowerGamerBR** [comment] 2018-05-24 15:54
@jknack 

```
		/** Start a websocket at /ws and send back JSON: */
		ws("/ws", { handler, ws ->
			/** Send back message: */
			val aaa = handler.session().get("foo").value()
			ws.onMessage({ ws.send("Received Message! ${aaa}") });

			/** Broadcast to all clients: */
			ws.broadcast("Hello World!!!");
		})
```

Same exception 😢

**Comment by MrPowerGamerBR** [comment] 2018-05-24 15:55
And just to be 100% sure, I copied exactly the same code as yours on your previous comment

```
package com.mrpowergamerbr.loritta.tictactoe

import com.mrpowergamerbr.loritta.Loritta
import com.mrpowergamerbr.loritta.frontend.LorittaWebsite
import com.mrpowergamerbr.loritta.frontend.views.GlobalHandler
import org.jooby.Jooby
import org.jooby.Kooby
import org.jooby.mongodb.MongoSessionStore
import org.jooby.mongodb.Mongodb
import java.io.File
import kotlin.concurrent.thread

class TicTacTest : Jooby() {
	init {
		port(4568)
		securePort(4569)
		get("hello") { req, res ->
			req.session()["foo"] = "hello"
			res.send(File("C:\\Users\\Whistler\\Documents\\TavaresBot\\tic_tac_toe\\index.html").readText())
		}
		assets("/**", File("C:\\Users\\Whistler\\Documents\\TavaresBot\\tic_tac_toe\\").toPath())
		/** Start a websocket at /ws and send back JSON: */
		ws("/ws", { handler, ws ->
			val test = handler.session().get("test")
		})
	}
}

fun main(args: Array<String>) {
	val website = thread(true, name = "Website Thread") {
		org.jooby.run({ TicTacTest() })
	}
}
```

And...
```
[12:55:12.760] [nio-worker-3-2/ERROR] o.j.WebSocket: execution of WS/ws resulted in exception
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block
  at org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2964)
  while locating org.jooby.Response

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)
	at org.jooby.internal.RequestImpl.require(RequestImpl.java:481)
	at org.jooby.Registry.require(Registry.java:233)
	at org.jooby.internal.RequestImpl.ifSession(RequestImpl.java:557)
	at org.jooby.internal.RequestImpl.session(RequestImpl.java:545)
	at com.mrpowergamerbr.loritta.tictactoe.TicTacTest$2.onOpen(TicTacTest.kt:24)
	at org.jooby.internal.WebSocketImpl.connect(WebSocketImpl.java:428)
	at org.jooby.internal.HttpHandlerImpl.lambda$handle$4(HttpHandlerImpl.java:484)
	at org.jooby.internal.netty.NettyWebSocket.connect(NettyWebSocket.java:362)
	at org.jooby.internal.netty.NettyRequest.lambda$null$1(NettyRequest.java:408)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:78)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:73)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker$1.operationComplete(WebSocketServerHandshaker.java:200)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker$1.operationComplete(WebSocketServerHandshaker.java:194)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:52)
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:697)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:259)
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:339)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:409)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:360)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1376)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:1746)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:757)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:734)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:533)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1129)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block
	at org.jooby.internal.RequestScope.getScopedObjectMap(RequestScope.java:255)
	at org.jooby.internal.RequestScope.lambda$scope$0(RequestScope.java:230)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 66 common frames omitted
```

**Comment by MrPowerGamerBR** [comment] 2018-06-16 13:37
@jknack I changed your code a bit for testing purposes
```kotlin
import com.google.inject.spi.Message
import org.jooby.Jooby
import java.io.File
import java.util.function.Supplier

class App : Jooby() {

	init {
		use("*") { req, rsp ->
			req.session().set("foo", "hello")
		}
		get("*") { req, rsp ->
			rsp.send(File("C:\\Users\\Whistler\\Documents\\WebSockets\\test.html").readText())
		}

		/** Start a websocket at /ws and send back JSON:  */
		ws("/ws") { req, ws ->
			val `var` = req.session().get("foo").value()
			ws.send(`var`)
			/** Send back message:  */
			ws.onMessage { msg -> ws.send(Message(msg.value())) }

			/** Broadcast to all clients:  */
			ws.broadcast(Message("New client connected to: " + ws.pattern()))
		}.produces("json")
	}

	companion object {

		@JvmStatic
		fun main(args: Array<String>) {
			Jooby.run(Supplier<Jooby> { App() }, *args)
		}
	}

}
```

And I loaded this HTML file on my browser
```html
test

<script>
var connection = new WebSocket('ws://127.0.0.1:8080/ws');

// When the connection is open, send some data to the server
connection.onopen = function () {
  connection.send('Ping'); // Send the message 'Ping' to the server
};

// Log errors
connection.onerror = function (error) {
  console.log('WebSocket Error ' + error);
};

// Log messages from the server
connection.onmessage = function (e) {
  console.log('Server: ' + e.data);
};
</script>
```

```
[10:34:02.938] [nio-worker-3-3/ERROR] o.j.WebSocket: execution of WS/ws resulted in exception
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block
  at org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2980)
  while locating org.jooby.Response

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)
	at org.jooby.internal.RequestImpl.require(RequestImpl.java:481)
	at org.jooby.Registry.require(Registry.java:233)
	at org.jooby.internal.RequestImpl.ifSession(RequestImpl.java:557)
	at org.jooby.internal.RequestImpl.session(RequestImpl.java:545)
	at App$3.onOpen(App.kt:19)
	at org.jooby.internal.WebSocketImpl.connect(WebSocketImpl.java:428)
	at org.jooby.internal.HttpHandlerImpl.lambda$handle$4(HttpHandlerImpl.java:484)
	at org.jooby.internal.netty.NettyWebSocket.connect(NettyWebSocket.java:362)
	at org.jooby.internal.netty.NettyRequest.lambda$null$1(NettyRequest.java:410)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block
	at org.jooby.internal.RequestScope.getScopedObjectMap(RequestScope.java:255)
	at org.jooby.internal.RequestScope.lambda$scope$0(RequestScope.java:230)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 21 common frames omitted
```
And the "OutOfScopeException" was thrown, *maybe* the issue is because I'm not using Secure WebSockets? I tried using Secure WebSockets but Jooby thrown an exception due to invalid SSL, but then again, my hacky code I shared above works without having a Secure WebSocket connection, so I guess that wouldn't be an issue. (in production, I run Jooby without SSL, since connections are made thru Cloudflare (https connection) -> Nginx proxy (http connection) -> Jooby (http connection))

**Comment by rjaros** [comment] 2019-04-10 16:12
Hello,
Is there any chance this issue will be addressed? Or should I rather wait for websockets support in Jooby2?

**Comment by jknack** [comment] 2019-11-24 14:12
Fixed in 2.x

**Closed by jknack** 2019-11-24 14:12 UTC
Labels: bug
