### ISSUE TITLE
jooby 3: next major release

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#1712] opened 2020-05-12 19:41 UTC
This is an open discussion of what we want for Jooby 3.x. For now we will start a discussion here and then cleanup ideas/features to a wiki page (or similar).

Beside is going to be a major release... I'm not planning to break compatibility like we did in 1.x -> 2.x upgrade, so:

- Web site will keep as it is today: https://jooby.io, same goes for Java package: io.jooby.
- The 3.x source code will be just a refactor of existing 2.x source code (not an entire rewrite). Unless something really bad/ugly come up, you will be able to upgrade doing a search/replace session.

Some notes I have so far:
- Review Context API add getter/setter for almost everything (simplify unit test)
- Keep minimum request/response related method into Context (simply context API)
- Add getRequest/getResponse method to Context and add all the necessary getter/setter to each of these new Request/Response API
- Remove bytecode analysis for return types and get back reactive operators (similar to 1.x)
- Remove asm from jooby core
- Kotlin Normal route vs Coroutine route try to simplify usage and remove the HandlerContext object. Favor usage of `fun some(ctx: Context)` and then `get("/route", ::some)`. This probably implies that lambda body route are bind to Context itself
- Rename FileUpload.destroy to close and make it Closable
- Value API make them getter friendly
- Remove runApp. Replace. with new App()
- Rename Jooby class to WebApp?
- Use application.logback.xml so we don't have initialization issues

**As always, your feedback is welcome**

**Comment by Sayyiditow** [comment] 2020-05-18 01:56
These look good. Can you also include adding of setter methods for the ModelAndView class so we don't have to re-initialize the class in case we are changing the view name for the same route?

Having to do this right now, in stead just set the view name based on the request parameters. Other routes can have multiple such initialization which looks expensive?

``get("/", ctx -> {
            String asyncPage = ctx.queryString();
            ModelAndView modelAndView;
            if (Boolean.parseBoolean(asyncPage))
                modelAndView = new ModelAndView("index_async.ftl");
            else
                modelAndView = new ModelAndView("index.ftl");
            modelAndView.put("pageTitle", "Sayyiditow Tech - High Level Enterprise SPAs");
            
            return modelAndView;
        });``

**Comment by imeszaros** [comment] 2020-05-28 08:14
Nice to hear that compatibility with 2.x is kept in mind. We just started to use Jooby 2.x and planning with it for the long run, also planning to migrate our older codebases.

Huge thumbs up for the API refactoring for `Contect` -> `Request` + `Response`!

We ran into some problems with the Guice extension. In Jooby 1.x it was very convenient that you could inject request scoped objects into controllers / services. In Jooby 2.x it's only possible with some custom extensions implementing `@RequestScoped` and co. similarly to Jooby 1.x.

Could you briefly what does return value analysis and ASM in Jooby do?

**Comment by jknack** [comment] 2020-05-28 12:25
> Huge thumbs up for the API refactoring for Contect -> Request + Response!

Going to keep Context in 3.x, because feel it is better the single argument handler:

    get("/", ctx -> {...})

and not the two arguments

    get("/", (req, rsp) -> {...}

There are some method name collision will keeping everything in Context class. In 3.x going to only keep the most frequently used methods in Context class, while less frequently or more specific methods will be available in Request/Response classes. This helps to keep some common code in Context (jooby-core) and force server to implement more simple/basic Request/Response objects.

> Could you briefly explain what does return value analysis and ASM in Jooby do?

ASM helps to identify handler return types in lambda/script routes:

    get("/rx", ctx -> CompletableFuture.supplyAsync(() -> "..."));

So here ASM find the handler returns a completable future and:

- Run route handler in EventLoop
- Attach a completable listener and to send response when ready

Same for other reactive types from: rxjava and reactor
In 3.x this will requires some manual intervention (like in 1.x):

   use(new CompletableFutureAdaptor());
   get("/rx", ctx -> CompletableFuture.supplyAsync(() -> "..."));

Removing ASM give us:
- Even faster startup time
- Reduce memory in class space

**Comment by hc-codersatlas** [comment] 2020-06-08 12:06
Would removing ASM slow performance down? 

Would be good to add a jackson alternative such as dsljson since that's been 1 of the bottlenecks in techempower benchmarks :)

Maybe other security options besides a heavy weight like pac4j?

GraalVM aka native mode would be useful in a lot of places but might be a bit of work.

**Comment by jknack** [comment] 2020-06-08 12:25
> Would removing ASM slow performance down?

A bit on some specific use cases,  but not for usage on real application.

> Would be good to add a jackson alternative such as dsljson since that's been 1 of the bottlenecks in techempower benchmarks :)

Yea, nothing stop us from using dsljson today.  Due it requires an annotation processor, don't think we need to support as Jooby module. I keep jackson in TEB bc is a real library that works for complex use cases. Still, we. could rewrite the benchmark to use. something more lightweight

> Maybe other security options besides a heavy weight like pac4j?

Hahaha, feel something similar... but is there any security framework lightweight? 

> GraalVM aka native mode would be useful in a lot of places but might be a bit of work.

We did some work and got something working with 2.x, slf4j-simple logging and netty (think undertow didn't work). Removing ASM from core (actually from runtime) will help to make Graal image.

**Comment by hc-codersatlas** [comment] 2020-06-08 12:45
> Yea, nothing stop us from using dsljson today. Due it requires an annotation processor,

dsljson has a reflection option, which is still quite a bit faster.

> but is there any security framework lightweight?

If it's just basic auth or jwt (via e.g. jjwt) then it doesn't really need a "framework". 

> netty (think undertow didn't work)

Undertow 3 will be a wrapper around netty.

**Comment by jknack** [comment] 2020-06-08 12:52
> dsljson has a reflection option, which is still quite a bit faster.

cool, I didn't know it.

> If it's just basic auth or jwt (via e.g. jjwt) then it doesn't really need a "framework".

Yea, I usually do header auth so never use pac4j. There is a jwt auth module too: https://jooby.io/modules/jwt-session-store/

> Undertow 3 will be a wrapper around netty.

Awful/wrong decision is you asked me. Found undertow super fast (faster than netty) and by far lot easy to work than netty. Also, it is a truly option/alternative to netty today. Don't want to be a wrapper over netty.
I believe Undertow API and execution model will be more or less the same (but around netty). Probably going to drop support for Netty when Undertow run on top of it.

**Comment by hc-codersatlas** [comment] 2020-06-08 13:17
> Found undertow super fast (faster than netty)

Depends. Netty has more features like OpenSSL support. There's a lot of options that can be turned on. Out of the box Undertow is faster. Netty is complex though I agree.

> Awful/wrong decision is you ask me.

Main focus is on moving off Wildfly (the main use of Undertow) and into Quarkus (which is Vertx/Netty). Makes sense as a business - Netty has a lot more users in the community, e.g. Twitter, Google and Apple. I don't think it's wise for IBM to be re-implementing HTTP3 and many of the other missing features in Java land when it comes to it so consolidating was a good move.

Undertow hasn't had major features properly in a long time. It was almost a solo project and the ex-lead now moved to Quarkus. I really like the API of Undertow!

> Probably going to drop support for Netty when Undertow run on top of it.

Would be good to compare once Undertow 3 or 4 comes out to see how much overhead they've added too.

> There is a jwt auth module too

Is it a documentation issue? The session store doesn't feel like authentication so maybe I'm misunderstanding it...

Simple caching with annotations and some assistance with API versioning would be good too.

**Comment by jknack** [comment] 2020-06-08 13:44
I'm not going to say anything about Quarks... 😄 

> Is it a documentation issue? The session store doesn't feel like authentication so maybe I'm misunderstanding it...

Integrates the HTTP Session with JWT token using a cookie or header.

> Simple caching with annotations and some assistance with API versioning would be good too.

Yea, this is more or less: module (so we can probably add something today). This thread is more for core changes. Do you have an example of API versioning?

**Comment by hc-codersatlas** [comment] 2020-06-09 03:11
> Do you have an example of API versioning?

@Version(1) -- so via annotations on methods / classes and option to set it as either via header, request parameter, or part of the uri to request it. Can return via uri, mime type or header etc.

**Comment by inaiat** [comment] 2020-06-18 19:26
kotlinx.serialization support!

Would be great to see some native support for https://github.com/Kotlin/kotlinx.serialization

Thanks!

**Comment by a1730** [comment] 2020-08-25 12:06
**Please add a Server API.** 

This will allow for other server implementations.

Currently we have a choice of Jetty or Netty (Undertow is moving to Netty) with Jooby.  However, Netty is very low level and we found their API evolution can be unsettling for production deployments especially when you have multiple Netty based apps with each dependent library asking for different versions of Netty.
There are other good Java based servers [see ActiveJ](https://github.com/activej/activej) that can host Jooby if there were a Jooby server contract for us to validate our code.

Async Java programming may not be much a gain once project Loom becomes reality. We played with Jetty with Loom (early access) on Jooby - it worked, our code was a joy to read, but we could not certify against a server contract.

**Comment by jknack** [comment] 2020-08-25 12:15
The API is: io.jooby.Context, a server implementation must provide a context. It is impossible to require more than io.jooby.Context there are all type of oddities between servers.

**Comment by a1730** [comment] 2020-08-25 12:45
Awesome. 
Thank you.

**Comment by jonnii** [comment] 2020-09-03 14:32
@jknack assuming this isn't around the corner would it be possible to cut a 2.x release with support for kotlin 1.4?

**Comment by jknack** [comment] 2020-09-03 14:35
@jonnii master branch is running on Kotlin 1.4, so next release (2.9.0) comes with it and yea, no work has been done yet on 3.x 👍

**Comment by ravihara** [comment] 2020-09-12 07:00
> This is an open discussion of what we want for Jooby 3.x. For now we will start a discussion here and then cleanup ideas/features to a wiki page (or similar).
> 
> Beside is going to be a major release... I'm not planning to break compatibility like we did in 1.x -> 2.x upgrade, so:
> 
>     * Web site will keep as it is today: https://jooby.io, same goes for Java package: io.jooby.
> 
>     * The 3.x source code will be just a refactor of existing 2.x source code (not an entire rewrite). Unless something really bad/ugly come up, you will be able to upgrade doing a search/replace session.
> 
> 
> Some notes I have so far:
> 
>     * Review Context API add getter/setter for almost everything (simplify unit test)
> 
>     * Keep minimum request/response related method into Context (simply context API)
> 
>     * Add getRequest/getResponse method to Context and add all the necessary getter/setter to each of these new Request/Response API
> 
>     * Remove bytecode analysis for return types and get back reactive operators (similar to 1.x)
> 
>     * Remove asm from jooby core
> 
>     * Kotlin Normal route vs Coroutine route try to simplify usage and remove the HandlerContext object. Favor usage of `fun some(ctx: Context)` and then `get("/route", ::some)`. This probably implies that lambda body route are bind to Context itself
> 
>     * Rename FileUpload.destroy to close and make it Closable
> 
>     * Value API make them getter friendly
> 
>     * Remove runApp. Replace. with new App()
> 
>     * Rename Jooby class to WebApp?
It could be named as JoobyWeb or just Jooby as it is now.
> 
>     * Use application.logback.xml so we don't have initialization issues
An overridable logger configuration similar to what log4j2 provides, might be considered too. JSON logging could be helpful these days using logger specific appenders, then.
> 
> 
> **As always, your feedback is welcome**

**Comment by jknack** [comment] 2020-09-12 13:26
@ravihara Log4j2 is supported in Jooby 2.x today https://jooby.io/#configuration-logging-log4j2 and you can use `log4j.json` to configure it.

**Comment by ravihara** [comment] 2020-09-12 15:48
> @ravihara Log4j2 is supported in Jooby 2.x today https://jooby.io/#configuration-logging-log4j2 and you can use `log4j.json` to configure it.

Well! What I was suggesting was, can we have log4j2 as an alternate to slf4j instead of using it via slf4j facade. Something similar to how Vert.x does it. If the plan is to stick to slf4j, I would rather continue to use logback mainly for its native implementation of slf4j api.

**Comment by jknack** [comment] 2020-09-12 16:25
Oh got it. will check what vertx does and yes! would like to remove logging from core

**Comment by imeszaros** [comment] 2020-09-27 16:35
Dependency on the Config library could be also dropped to:
- be more lightweight
- allow to use the library of choice

Configuration could be done by a DSL like:

```java
{
  configure(cfg -> {
    cfg.serverOptions(so -> {
      so.setPort(90);
      ...
    });
    cfg.application(app -> {
      app.setName("MyApp");
      ...
    });
    // or
    cfg.applicaton(new AppConfig().setName("MyApp"));
  });

  // getting a property
  config().serverOptions().port();
}
```

And the integration with the Config library could be provided by a module to keep compatibility of course. Users could inject the instances provided by the module to get their own config entries:

```
{
  require(Config.class).getString("my.entry");
}
```

**Comment by a1730** [comment] 2020-09-28 01:01
Time for JPMS review?
We tried to use modules in the past and I believe there were split modules between jooby-core and jooby-test.

**Comment by agentgt** [comment] 2020-11-20 18:41
I agree with @imeszaros on making Config library pluggable.

I have done extensive testing on startup time for our code base and our microservices and the number one thing that really slows startup time for an application before it starts connecting to databases or using massive reflection (e.g. Spring) is resource loading from the classpath.... and I don't mean classes.

For example Log4J2's startup time is 300ms and this is because of the excessive of resource looking up of property files.

Ditto for logback however logback can be loaded using just the service loader (I put that in a long time ago for ceki).

I haven't tested lightbends config time wise for awhile but I know by default it does some resource looking up and I think quite a bit if it can't find config files.

The convenience method ConfigFactory.load() loads the following (first-listed are higher priority):

From lightbend config project page:

```
system properties
application.conf (all resources on classpath with this name)
application.json (all resources on classpath with this name)
application.properties (all resources on classpath with this name)
reference.conf (all resources on classpath with this name)
```

Now I think I got around this problem by doing something like:

```
	public static Environment createEnvironment() {
		ClassLoader cl = Thread.currentThread().getContextClassLoader();
		if (cl == null) {
			cl = JoobyFactory.class.getClassLoader();
		}
		return new Environment(cl, Environment.defaults(), "ignore");
	}
```

Our microservices jars are like down to 9 Megs and I take great pleasure in every 200 KBs we can shed from them so no hard dependency on Config would be a nice feature in my book .

**Comment by agentgt** [comment] 2020-11-20 19:01
@jknack 

> Oh got it. will check what vertx does and yes! would like to remove logging from core

On removing SL4J take a look at Min log: https://github.com/EsotericSoftware/minlog

I'm not saying you depend on the library but rather take the code and adapt it for internal logging of Jooby. 

Then you make multiple jars for info/debug/warn etc or delagate to SL4J. You can make a production level jar that will true compile time NOOP for INFO and below but fail horrifically on ERROR by dynamically loading SL4J and then logging message and then falling back to System.err (this is how I do it for one of our libraries).

**Comment by jknack** [comment] 2020-11-20 20:35
will definitely look at minlog, but yea that is the issue with logging and config: we need to add a new contract/abstraction for each of them... which I don't like it.

**Comment by agentgt** [comment] 2020-11-27 15:26
> we need to add a new contract/abstraction for each of them... which I don't like it.

We kind of already have it: [Value](https://www.javadoc.io/doc/io.jooby/jooby/latest/io/jooby/Value.html) and Environment.getProperty.

Another alternative is Microprofile Config: https://github.com/eclipse/microprofile-config which is a config facade.

One thing I kind of don't like about Jooby is it tries to do too much initialization and thus is kind of getting into DI boot strapping and wiring space. This is indicative of all the modules that are not strictly related to HTTP.

That is initialization for our Jooby projects:

 1. Config framework
 1. Logging Framework
 1. Possibly Dependency Injection framework but lately we don't use DI
 1. Database layer
 1. Event system layer (kafka, rabbit, etc)
 1. And finally HTTP layer aka Jooby

Jooby seems to want to do:

1. Logging framework (this because SLF4J static initialization is stupid and requires it to be practically the first thing that gets executed in every java application... thus logback with its XML dialect is the first thing that gets executed)
1. Jooby
1. Jooby modules

Because we do the initialization I don't find most of the Jooby modules at all useful especially the database ones. 

**The problem is the main requirement for sophisticated configuration is because Jooby has a modules system.**

I'm not strongly against the module system but that is why the config library seems to need to be complicated. I guess my question is other than the HTTP message encoding modules are folks using the other modules?

See these days I find we don't need complicated configuration libraries nor dependency injection because we no longer make giant monolithic applications but instead do microservices. Thus if there is any config it needs to be flexible in terms of source and  available over a network none of which lightbend config offers (our internal config framework does). What isn't really needed is the converting that lightbend config offers... `String getProperty(String k)`  is mostly good enough (IMO).

**Comment by jknack** [comment] 2020-11-27 17:33
Good summary for your projects, but yea after 6 years of doing Jooby. I'm sure people find module useful.
Installing modules (compared with 1.x) is just a call to `module.install(this)`.. nothing more and if you don't want or like them, just don't install/add them. There is no overhead.

Slf4j was the default logging in Java in all these years, with logback native implementation. No big complains about until log4j2 got finally out. So if you see now it is basically three possible/real implementation (in practice or general): logback, log4j2, System.out.

Config from type safe is a simple, lightweight and easy to use configuration library.

Configuration over network is an over kill... You can't read a property and save it in a String (which is the minimal basic/use case). Instead you need a reference to the entire configuration or reference to that string... feel too much.

Beside this and due 2.x took a different approach than 1.x I believe we could:

- Use java.util.Properties for configuration (no external dependencies, nothing)
- Write a log wrap, that bootstrap logback or log4j2 as modules

**Comment by agentgt** [comment] 2020-11-27 17:54
> Configuration over network is an over kill... You can't read a property and save it in a String (which is the minimal basic/use case). Instead you need a reference to the entire configuration or reference to that string... feel too much.

Most cloud providers provide metadata services as well as there is also vaults for secrets (See hashicorp vault).

I’m not saying you provide a distributed config system. I’m saying use a library that is pluggable or provide an SPI. For example  Use Micro profile config and let it default to lightbend config. 

Javalin, spring, micronaut, quarkus, helicon and more all provide a way to plug in your own configuration sources. I mean it’s just key, values.

Also Config from lightbend is hardly simple. It has its own config parser (hucon), interpolation, and resource loading. It also can map config to objects via reflection. It takes longer for config lightbend to load up its default stuff than it takes for our internal config to use google clouds meta data service to fetch plain properties! I’m serious!

And yet with all that complexity it doesn’t have dynamic properties nor can you change the source. I mean I suppose you can try to implement configs interface and disregard its javadoc on not to do that.

But I can see how the modules are useful to other folks.

**Comment by agentgt** [comment] 2020-11-27 18:10
I also don’t have that much problem with SLF4J provided it isn’t kicked off on unit testing and that internal network logging isnt done with it (eg tight loop trace statements).

I just meant if you are going to get rid of it in core you might as well have it go really fast and not auto initialize.

**Comment by agentgt** [comment] 2020-11-27 19:01
Hmm I guess you can kind of alter how lightbend Config loads with [ConfigLoadingStrategy](https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/ConfigLoadingStrategy.java). I remember looking to feed custom sources into lightbend config and had some issues a couple years ago.


Regardless it takes less than 10ms to call google clouds meta data service and to load it with Jackson or straight up java.util.Properties. The below loads all the key, values into Jackson but you can pull distinct keys  as well. Loading up lightbend config on the other hand is at least 100ms last time I checked.... so no network is not slow or overkill in the cloud. Remember the filesystems are basically on a network.

	static String GCLOUD_URL =
			"http://metadata.google.internal/computeMetadata/v1/project/attributes/" + "?recursive=true";

	protected static Map<String, String> gcloudMap(
			String url)
			throws IOException {
		URL obj = new URL(url);
		HttpURLConnection con = (HttpURLConnection) obj.openConnection();
		try {
			con.setConnectTimeout(200); // don't worry google is extremely fast.
										// If
										// slow something is wrong.
			con.setReadTimeout(2000);
			con.setRequestMethod("GET");
			con.setRequestProperty("Metadata-Flavor", "Google");
			con.getResponseCode();
			int code = con.getResponseCode();
			if (code > 400) {
				throw new IOException("GCloud server had issue");
			}
			try (InputStream is = con.getInputStream()) {
				ObjectMapper om = new ObjectMapper();
				@SuppressWarnings("unchecked")
				Map<String, String> m = om.readValue(is, Map.class);
				m = new LinkedHashMap<>(m);
				return m;
			}
		}
		finally {
			if (con != null) {
				con.disconnect();
				con = null;
			}
		}
	}

**Comment by jknack** [comment] 2020-11-28 20:33
> I just meant if you are going to get rid of it in core you might as well have it go really fast and not auto initialize.

Yea, we need to get rid of `logback.xml` and probably pick/suggest another name like Spring does. But also, is a bit hard bc no matter how you call it... if you uses a `static` logger then it is going to bootstrap anyway :S

> Javalin, spring, micronaut, quarkus, helicon and more all provide a way to plug in your own configuration sources. I mean it’s just key, values.

Yea, something like that. Probably have our own basic API and allow to customize by providing `java.util.Map` (like Spring does)

> Hmm I guess you can kind of alter how lightbend Config loads with ConfigLoadingStrategy. I remember looking to feed custom sources into lightbend config and had some issues a couple years ago.

I prefer to not go with something like this (unless it is strictly necessary). One goal/principle of Jooby module system is they add as little as possible over a external library, otherwise it is maintainable over time.

**Comment by a1730** [comment] 2020-12-13 06:13
> Yea, something like that. Probably have our own basic API and allow to customize by providing `java.util.Map` (like Spring does)
Please  make sure the configuration format you settle on allows for comments. The practice of JSON configuration file format is sub-optimal for dev-ops.

**Comment by hc-codersatlas** [comment] 2020-12-20 05:52
Would be nice to remove the dependency on Config and use java.util.Properties. Faster startup too. For the current use case it looks similar enough.

Slf4j continues to be a great standard. Don't understand what the problem is. If it's logback and xml - don't use logback? Plenty of better alternatives. You can programmatically configure log4j2 if needed. Been using tinylog lately, which is light weight and fast. 

Logging should be started before everything else anyhow - visibility is important. Starting up a logger shouldn't be slow.

**Comment by agentgt** [comment] 2020-12-20 12:44
The problem is logging needs to be configured much more than configuration needs logging.

One of the reasons why logback, old log4j, and new log4j2 are overly complex is that they have to provide boot strap configuration options because they ~~have~~ want to be the first to start.

I argue with fairly strong opinion you need boot strap configuration first and if there was a standard for this earlier a lot of complexity could have been removed from the logging libraries.

Even worse because of this config first dependency you often have frameworks boot logging than load the config and the reload all of logging again. This is what dropwizard does (or did) and it’s slow as shit.

**Comment by j2eekingcn** [comment] 2020-12-23 09:38
Before I wrote a project with v1 version, now I upgrade to v2, the code is basically changed. I hope that the api and method of v3 will not undergo major changes. One of the advantages of Java is backward compatibility. I hope Jooby can also Not so radical, in short, I hope jooby gets better and better

**Comment by agentgt** [comment] 2021-04-19 00:53
Some recent thoughts after using jooby in over 10 services I would say more and better MVC annotation support would be appreciated.

The most requested being default/nonnull support for query/form parameters (ie required and a default value).

That is in several MVC/JAXRS annotations APIs you can do something like 

```
@RequestParam(value = "name", default = "someValue", require = true)
```

I believe Spring MVC supports the above.

Also `@QueryParam SomeObject someObject` currently will cause the MVC APT code generator to generate byte code that calls `ctx.query().convert(...)` and not `ctx.query("someObject").convert`. `ctx.query().convert` will attempt to use the enitire query string to do conversion.  I worked with @jknack  on Value converters a while back so I take responsibility on this not being communicated but sometimes you want a single parameter to convert to a Bean (and now Record) vs the entire Query String.

Anyway I think we need a `@QueryParams` (notice the plural "s") that will always generate byte code for `ctx.query()` vs `ctx.query("nameOfParameter")`.

**Comment by cmitchell** [comment] 2021-06-02 17:25
Any idea when the 3.x version will be released?  Or even a 2.9.7 version that includes your recent updates to the gradle plugin?   I'm excited to see that you've recently updated jooby to be compatible with a much more recent version of gradle. I would like to be able to take advantage of the joobyRun task, but could continue to just manually execute the jar instead if neitherversion is close to being released.

**Comment by agentgt** [comment] 2022-05-27 12:33
@jknack Just some more thoughts on 3.0. 

For 3.0 we might want to checkout EA Loom builds. I believe it will be preview in 19. I think Jetty is the only one that takes advantages of the of new threading model. I am going to experiment running loom with Jooby to see what happens.

3.0 should also just switch to JDK 17 and use the builtin JDK Flow for the reactive stuff.

Consequently 3.0 should be modularized....  however I guarantee that will probably break a few things.

**Comment by jknack** [comment] 2022-05-27 13:43
> 3.0 should also just switch to JDK 17 and use the builtin JDK Flow for the reactive stuff.

isn't too much? I was planning to go with JDK 11

> Consequently 3.0 should be modularized

I'm lost here... Never used them, not sure what to do or were to start. Did you use modules?

**Comment by agentgt** [comment] 2022-05-28 02:59
> isn't too much? I was planning to go with JDK 11

[Spring 6 and latest JEE are baselining for Java 17](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6)

In my experience there are two groups of users/projects: Java 8 and everyone else. Everyone else can and should run latest greatest. If not the latest LTS which is 17.

The problem with not picking 17 is that other projects will and you might find you will need to do an upgrade sooner than you like (also 11 will be EOL in 4 years).

> I'm lost here... Never used them, not sure what to do or were to start. Did you use modules?

Basically module-info.java in packages which I'm sure you know of. Eclipses support of this is better than intellijs but both of them are at odds with Maven. 

Anyway if you don't support modules people that do will get annoyed. Spring is even planning on doing it and they have far more problems given the amount of reflection they use.

We are actually planning on biting the bullet and moving to adding module-info.java albeit are reasons for not doing it sooner are different than other peoples (as well as our reasons for doing it).

The reason we haven't done it sooner is because the Maven Shade plugin executable uber jars cannot support modularity (since there can only be one module-info.java). Given docker and docker layers as well as JLink we are considering abandoning this approach as it also seriously slows down build time.

The reasons we want to do it is because I'm a firm believer of compile time separation rules (e.g. database code separated from front end code) aka modularity.

You can do this with Maven but its actually really painful as you either need dummy projects so that you can pull transitive dependencies as `<scope>runtime</scope>`. That is there is no way in Maven to  make a library/module that uses other libraries as `<scope>compile</scope>` but then say that dependency is `<scope>runtime</scope>` so that project that depends on the library only sees your library in the classpath. The other way to do this is use/abuse `<optional>true</optional>`. Or you just put shit in an "internal" package and so don't touch but that still doesn't fix transitive deps.

Let me give you an example. Ideally you can think of Jooby core as two jars/modules. Jooby and Jooby internal (`io.jooby.internal`). This is because all the stuff in regular Jooby is compile time dep where as internal is runtime and should only be visible to Jooby (`io.jooby`). However to make to separate jars like that in Maven is nontrivial (e.g. spec and implementation) because of the problems I described earlier.

Why does that matter... well in large particularly monolithic projects developers will use transitive libraries or private implementations when they should not (usually its like commons lang or guava). It also minimize the visible namespace so that you see less stuff when you "ctrl-space" (well Eclipse does... intellij has a tendency to show everything even if the dependency is not added to that module but is in some other project but let's ignore that).

Java Modules fixes the transitive dependency scope as compile problem while also eliminating the need for extra jars or modules just to fix maven scoping issues.

Anyway I can help modularize Jooby. I don't think it will be a lot of work.

**Comment by lucaguada** [comment] 2022-06-22 15:06
Yes, please, I vote for:
- Java Platform Module System support; it may be easier than trying to adapt Jooby to GraalVM;
- minimum JDK17 version requirement; with JPMS support, no one will realize what JDK is under the hood.

**Comment by imeszaros** [comment] 2022-06-29 06:59
> Anyway I can help modularize Jooby. I don't think it will be a lot of work.

@agentgt If that happens, please involve me somehow. I would like to learn :)

**Comment by cmitchell** [comment] 2022-06-29 10:31
I would like to throw in my support for JDK 17

**Comment by agentgt** [comment] 2022-09-11 15:02
@imeszaros @jknack  and others I was able to throw a tiny bit of time at modules and it appears undertow is shockingly not a module yet. SLF4J 2.0 luckily is now available and has full module support so at least one core dep is fully compliant. javax.inject is now jakarta which is modularized so that is tedious upgrade of namespace change but very low risk. There probably is even a version of old javax.inject with a different maven coord that is modularized.

I'm surprised by undertow but my guess is the OSS team on Red Hat is more focused on vertx and Quarkus these days. Also undertow I believe has or had plans to switch to netty instead of xnio. It is a shame for us because we use undertow as some of our services use the traditional Servlet spec.

I bring this up because perhaps Jooby 3.0 should target vert.x in lieu of undertow. Perhaps vert.x support should be added to 2.0 to help the migration for those that use undertow like we do. That being said vert.x is really just a wrapper around netty so maybe it isn't even worth it.

**Comment by jknack** [comment] 2022-09-11 15:51
fyi @agentgt @imeszaros I started to work on 3.x. The main branch is now 3.x

I don't like the idea to run on top of adding vert.x and 2.x no more big changes there.

**Comment by agentgt** [comment] 2022-09-12 12:51
I agree. I just floated the vertx option if folks wanted to have a single underlying HTTP server/servlet implementation throughout their code base but as I said it really adds very little value to jooby as vertx itself is built on netty and jooby already is. If undertow switches to Netty then undertow is basically like vertx and doesn't add much value.

I guess the point I'm making is I would consider Undertow in jooby 3.0 lower priority given its apparent future and possibly replaced. Loom may change a lot of stuff so something like [Helidon Nima](https://github.com/oracle/helidon/tree/main/nima) maybe a better 3rd option to explore.

**Comment by jknack** [comment] 2022-12-05 21:34
First milestone is out: https://github.com/jooby-project/jooby/releases/tag/v3.0.0.M1

Still lot more to do.

**Comment by agentgt** [comment] 2023-01-13 14:10
@jknack is there a possible chance we can add automatic modules in the META-INF/MANIFEST.MF for  v2.x?

The reason being is it will make it easier for me to test 3.x on our code base by swapping them out (I know there are api changes but I can deal with that) while still retaining a module-info in our projects.

**Comment by jknack** [comment] 2023-01-13 14:22
I don't have time to do it but also isn't a good idea. I don't want to get bugs, questions on 2.x around modules.

**Comment by agentgt** [comment] 2023-01-13 16:23
Yeah I was thinking the same while driving that I will just upgrade v3 across the board that way I can better help you as it will get confusing for me if we have issues.

Plus I assume v3 will get updates faster anyway and you generally accept PRs from me so I'll go ahead with it.

**Comment by jknack** [comment] 2023-01-13 16:25
Right. 2.x will go to maintenance mode, no more (new) changes there.

**Comment by Blquinn** [comment] 2023-01-24 18:53
@agentgt @jknack I played around with enabling virtual threads on Jetty as well as a super bare bones Helidon Nima server implementation for Jooby. Let me know what you think. I know this isn't exactly related to the release, but I saw you all talking about loom up above. Maybe we can enable the Jetty virtual thread options if you're on Java 19 somehow?

[Jetty Loom Branch](https://github.com/Blquinn/jooby/tree/jetty-loom)

[Helidon Nima Server Branch](https://github.com/Blquinn/jooby/tree/helidon-nima)

**Comment by agentgt** [comment] 2023-01-24 21:09
@Blquinn 

I guess what I'm saying is the easiest thing to do for now is to make separate projects for nima and jetty that are outside of jooby. Use the ServiceLoader registration to make your own Servers. You will have to duplicate jetty logic for now.

That way you avoid jooby code base locked on 17 (albeit there are ways to compile with multiple jdks in maven it isn't worth it).

Then the instructions are simple. Tell whoever to include your module (maven runtime dep) instead of jooby-jetty.

**Comment by Blquinn** [comment] 2023-01-27 04:28
@agentgt Yea I did suspect that copying everything would probably be the easiest way. Thanks for the info though. I'm somewhat familiar with ServiceLoader because I had to use it already for nima to work.

I guess I'm wondering if it's worth setting up a separate module, I'm not really sure if anyone will be interested in using this, or not. Jetty at least is basically ready to go because its just a couple lines of code, maybe that would be worth it.

**Comment by agentgt** [comment] 2023-01-27 20:24
> 'm not really sure if anyone will be interested in using this, or not. Jetty at least is basically ready to go because its just a couple lines of code, maybe that would be worth it.

I'm sure they will assuming the quality is good (btw you might want to remove what I assume is an accidental kotlin dep). In fact I would be curious to see it in the [techempower results](https://www.techempower.com/benchmarks/#section=data-r21). Hell I was going to do what you are already doing myself I just didn't have the time. So sally forth with testing loom 👍

**Comment by Blquinn** [comment] 2023-01-28 21:35
@agentgt Okay, you've convinced me ;)

**Closed** 2023-10-28 23:41 UTC
Labels: help wanted, feedback
