### ISSUE TITLE
Websockets onClose not working

### ISSUE THREAD

**Issue by Dominilk** [jooby-project/jooby#2210] opened 2020-12-26 15:29 UTC
Hi!

For some weird reason, the onClose event is not called on my WebSockets when setting a handler using the configurator.

Regards
Dominik

**Comment by jknack** [comment] 2020-12-27 15:36
Hi,

Please provide a working example and the steps required to reproduce the problem.

Thanks

**Comment by Dominilk** [comment] 2020-12-29 22:17
Hi,

Here is an example:
```
public class Demo extends Jooby implements Initializer {

	/**
	 * 
	 */
	public Demo() {
		this.assets("/", "demo.html");
		this.ws("/ws", this);
	}
	
	@Override
	public void init(Context context, WebSocketConfigurer configurer) {
		configurer.onConnect(socket -> System.out.println("Socket connected!"));
		configurer.onClose((socket, status) -> System.out.println("Socket has been closed!"));
	}
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		Jooby.runApp(args, Demo::new);
	}

}
```
And the **demo.html** file
```
<!-- Just for demonstration purposes -->
<html>
	<body>
		<div id="info"></div>
		
		<script type="text/javascript">
			const connection = new WebSocket('ws://localhost:8080/ws');
			const info = document.getElementById('info');
			
			connection.onopen = function () {
				connection.send('Hello!');
			};
			
			connection.onerror = function (error) {
				info.innerHtml += "Error occured\n";
			};
			
			connection.onmessage = function (e) {
				info.innerHtml += "Server: " + e.data + "\n";
			};
			
			connection.onclose = function () {
				info.innerHtml += "Closed\n";
			};
		</script>
	</body>
</html>
```

When I close the tab or my whole browser the onClose callback (serverside) is never called.

**Comment by jknack** [comment] 2021-01-03 22:18
Edited your example by adding these lines:

```java
configurer.onMessage((ws, message) -> {
   System.out.println("Got " + message.value());
});
```

Without these callback Netty throws a NullPointerException. Going to fix it.

Once I added the onMessage callaback all the server implementation: Jetty, Netty and Undertow works as expected while closing a tab:

```
Socket connected!
Got Hello!
Socket has been closed!
```

Undertow shows an error that need to be silent up:

```
Socket connected!
Got Hello!
Socket has been closed!
[2021-01-03 19:16:43,777]-[worker I/O-1] ERROR app.App - Websocket resulted in exception: /ws
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
	at org.xnio.nio.NioSocketConduit.read(NioSocketConduit.java:289)
```

In short, the `onClose` works as expected on:

* Netty: if you listen for onMessage events
* Undertow: with an error that need to be silent up
* Jetty: works without problem

**Comment by Dominilk** [comment] 2021-01-04 17:18
Hi,
For some reason, it's still not working on my machine (I'm using the Netty backend). Even when I add the onMessage handler.

**Comment by jknack** [comment] 2021-01-04 17:28
I tried it again, still can't reproduce it. What JDK are you running?

Also, run `mvn dependency:tree` and paste the output here

**Comment by Dominilk** [comment] 2021-01-04 17:37
Okay, interesting...
I'm running Zulu 11/Java-SE 11 as it is currently set as default. I know tried with the JDK I usually use (JDK 13.0.1) still not working. Here's the output of the command you asked me to run:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< TestforJooby:TestforJooby >----------------------
[INFO] Building TestforJooby 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ TestforJooby ---
[INFO] TestforJooby:TestforJooby:jar:0.0.1-SNAPSHOT
[INFO] +- io.jooby:jooby:jar:2.9.4:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  \- com.typesafe:config:jar:1.4.1:compile
[INFO] \- io.jooby:jooby-netty:jar:2.9.4:compile
[INFO]    +- io.netty:netty-handler:jar:4.1.54.Final:compile
[INFO]    |  +- io.netty:netty-common:jar:4.1.54.Final:compile
[INFO]    |  +- io.netty:netty-resolver:jar:4.1.54.Final:compile
[INFO]    |  +- io.netty:netty-buffer:jar:4.1.54.Final:compile
[INFO]    |  +- io.netty:netty-transport:jar:4.1.54.Final:compile
[INFO]    |  \- io.netty:netty-codec:jar:4.1.54.Final:compile
[INFO]    +- io.netty:netty-codec-http:jar:4.1.54.Final:compile
[INFO]    \- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.54.Final:compile
[INFO]       \- io.netty:netty-transport-native-unix-common:jar:4.1.54.Final:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.857 s
[INFO] Finished at: 2021-01-04T18:36:46+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by jknack** [comment] 2021-01-04 17:45
Your pom looks OK, was expecting to find a versioning problem but nope.

can you try  on `2.9.5`?

Otherwise I'm lost, but sure what else to try.

**Comment by Dominilk** [comment] 2021-01-04 19:05
Unfortunately not working with 2.9.5 either.

**Closed** 2021-01-13 11:44 UTC
Labels: bug, netty, undertow
