### ISSUE TITLE
Regression with encoder: should consider route produce types

### ISSUE THREAD

**Issue by froque** [jooby-project/jooby#2804] opened 2023-03-02 16:45 UTC
issue #2613 and fix https://github.com/jooby-project/jooby/commit/9640984a949890948f15c472e47df3086005b890 introduces a regression for this example:

```java

  public static class Error {
    public String message;
  }

  public static class Errors {
    public List<Error> errors = new ArrayList<>();
  }

  @ServerTest public void shouldConsiderRouteProduces(ServerTestRunner runner) {
    runner.define(app -> {

      app.install(new JacksonModule());
      app.get("/pdf", ctx -> {

        if (ctx.header("Authorization").isMissing()){
          ctx.setResponseCode(StatusCode.UNAUTHORIZED).setResponseType(MediaType.json);
          final Errors errors = new Errors();
          final Error error = new Error();
          error.message = "No Authorization provided";
          errors.errors.add(error);
          return errors;
        }

        ctx.setResponseCode(StatusCode.OK).setResponseType(MediaType.byFileExtension("pdf"));
        byte[] dummyData = new byte[1024];
        Arrays.fill(dummyData, (byte) 0x0a);
        return new ByteArrayInputStream(dummyData);

      }).produces(MediaType.byFileExtension("pdf"), MediaType.json);

    }).ready(http -> {
      http.get("/pdf", rsp -> {
        assertEquals(StatusCode.UNAUTHORIZED_CODE, rsp.code());
        assertEquals(MediaType.json.toContentTypeHeader(StandardCharsets.UTF_8).toLowerCase(), rsp.header("Content-Type").toLowerCase());
        assertEquals("{\"errors\":[{\"message\":\"No Authorization provided\"}]}", rsp.body().string());
      });
      http.get("/pdf").prepare(req -> req.addHeader("Authorization", "foo")).execute(rsp -> {
        assertEquals(StatusCode.OK_CODE, rsp.code());
        assertEquals(MediaType.byFileExtension("pdf").getValue(), rsp.header("Content-Type"));
        assertEquals(1024, rsp.body().bytes().length);
      });
    });
  }
```

**Comment by jknack** [comment] 2023-03-03 14:29
Hi, 

Closer look (and after I merged your PR) I don't see how the changes you did in `HttpMessageEncoder` are related to your example. In your example you send/return an `InputStream` and set response-type too, so program flow never reach the changes you did just test and execute the `ctx.send(Inputstream)`.

```
 if (encoders != null) {
      // Content negotiation, find best:
      List<MediaType> produces = ctx.getRoute().getProduces();
      if (produces.isEmpty()) {
        produces = new ArrayList<>(encoders.keySet());
      }

      MediaType type = ctx.accept(produces);
      MessageEncoder encoder = encoders.getOrDefault(type, MessageEncoder.TO_STRING);
      return encoder.encode(ctx, value);
    } else {
      return MessageEncoder.TO_STRING.encode(ctx, value);
    }
```

with your tests is still good. Did you miss something in your example?

**Comment by jknack** [comment] 2023-03-03 14:34
never mind. I found it. The issue isn't around the InputStream, is with the errored response.

**Comment by jknack** [comment] 2023-03-03 14:53
The way it works is:

1) client must set `Accept` header. So here in your example you don't. This is what usually does a default call.
2) Due there is no explicit `Accept`, you must choose what is your preferred default encoder.

So, if you just change your code to:

```java
app.get("/pdf", ctx -> {

                if (ctx.header("Authorization").isMissing()){
                    ctx.setResponseCode(StatusCode.UNAUTHORIZED).setResponseType(MediaType.json);
                    final Errors errors = new Errors();
                    final Error error = new Error();
                    error.message = "No Authorization provided";
                    errors.errors.add(error);
                    return errors;
                }

                ctx.setResponseCode(StatusCode.OK).setResponseType(MediaType.byFileExtension("pdf"));
                byte[] dummyData = new byte[1024];
                Arrays.fill(dummyData, (byte) 0x0a);
                return new ByteArrayInputStream(dummyData);

            }).produces(MediaType.json, MediaType.byFileExtension("pdf"));
```

It works. The key here is that you want `json` to be your default type encoder.

Toughts?

**Comment by agentgt** [comment] 2023-03-03 19:31
I'm a little late but @froque referenced my original bug of #2613 .

FWIW I had to make my own MessageEncoders to deal with clients not having Accept header and or the ability to change the Accept based on parameter (e.g: `someurl?__accept=json`):

```java
class MediaTypeProducesMessageEncoder implements MessageEncoder {

	private Map<MediaType, MessageEncoder> encoders = new LinkedHashMap<>();

	@SuppressWarnings("null")
	@Override
	public byte @Nullable [] encode(
			Context ctx,
			Object value)
			throws Exception {

		MessageEncoder foundEncoder = null;
		for (var e : encoders.values()) {
			if (e instanceof IgnoreMediaTypeMessageEncoder imte) {
				if (imte.supports(ctx, value)) {
					foundEncoder = imte;
					break;
				}
			}
		}
		List<MediaType> produces = foundEncoder != null ? List.of() : resolveProduces(ctx);

		if (foundEncoder == null && !produces.isEmpty()) {
			MediaType mediaType = ctx.accept(produces);
			// This next condition disregards the user agents accept
			// This is debatable
			if (mediaType == null) {
				mediaType = produces.get(0);
			}
			foundEncoder = encoders.get(mediaType);
		}
		if (foundEncoder == null) {
			// This is the default behavior in HttpMessageEncoder
			MediaType mediaType = ctx.accept(new ArrayList<>(encoders.keySet()));
			foundEncoder = encoders.getOrDefault(mediaType, TO_STRING);
			if (foundEncoder instanceof IgnoreMediaTypeMessageEncoder) {
				log.warn("Found encoder was an IgnoreMediaTypeMessage Encoder. mediaType: {}", mediaType);
				foundEncoder = TO_STRING;
			}
		}
		return foundEncoder.encode(ctx, value);
	}

	@SuppressWarnings("null")
	static List<MediaType> resolveProduces(
			Context ctx) {
		List<MediaType> produces;
		String accept = ctx.query("__accept")
			.valueOrNull();
		if (accept != null) {
			produces = MediaType.parse(accept);
		}
		else {
			produces = ctx.getRoute()
				.getProduces();
		}
		return produces;
	}

	public void add(
			MediaType contentType,
			MessageEncoder encoder) {
		encoders.put(contentType, encoder);
	}

	private static final Logger log = LoggerFactory.getLogger(MediaTypeProducesMessageEncoder.class);

}
``` 

Then that static `resolveProduces` I call in my custom DefaultError handler:

```java
		List<MediaType> types = MediaTypeProducesMessageEncoder.resolveProduces(ctx);
		if (types.isEmpty()) {
			types = List.of(html, json, yaml, text);
		}

		MediaType type = ctx.accept(types);
```

Thus maintaining the same logic for error handling.

I don't know if the above helps but it has real world usage so perhaps some ideas can come out from it.

**Comment by jknack** [comment] 2023-03-04 00:00
custom encoders are OK, that is why Jooby let you do whatever you want. Here the issue occurs because:

1. There is no `Accept` header set. So clients, will set something that contains `*/*`.
2. You have a route that says: `application/pdf`, `application/json`
3. You didn't setup an encoder for `application/pdf`
4. Content negotiation looks into `application/pdf`, `application/json` and find the first that best matches `*/*`
5. Choose `application/pdf`
6. Try to find an encoder and it fails bc of point #3

If you set two types with same score, you will pick first bc it matches what clients requested `*/*`

So, solutions are:
1. set proper `Accept` type
2. or choose the want that should be the default encoder. That is why I suggested to move json first.

**Comment by agentgt** [comment] 2023-03-04 01:51
Yeah I don’t disagree. I only added my comment mainly for the OP.

IMHO these are fringe cases and as long as Jooby provides some means of override then I am good and clearly it was cause I did this in 2.x.

To be honest I am not a fan of the PR. I have not played around with it. Maybe it’s ok but I swear the logic was fine before.

**Closed** 2023-03-04 18:15 UTC
Labels: question
